# Copyright (c) 2019-2020 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
name: Matrix
on: [push]

jobs:
  job:
    name: ${{ matrix.os }} - ${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
        buildtype: [Release, Debug]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: NPM Install
        run: npm install
      - name: dir
        run: find ${{ github.workspace }}
        if: "!contains( matrix.os, 'windows')"
      - name: dir
        run: gci -recurse ${{ github.workspace }}
        if: contains( matrix.os, 'windows')
      - name: Run CMake with Ninja
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/CMakeLists.txt"
          buildWithCMakeArgs: "-- -v"
          buildDirectory: ${{ runner.workspace }}/build
          cmakeBuildType: ${{ matrix.buildtype }}
          # cmakeAppendedArgs: -DUSE_LUAJIT=${{ matrix.luajit }}

      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Upload lib headers
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: ${{ runner.workspace }}/build/external/libwebrtc/download/src/**/*.h

      - name: Upload lib binaries
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: ${{ runner.workspace }}/build/external/libwebrtc/build/${{ matrix.buildtype }}/obj/webrtc.lib

      - name: Upload lib binaries
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: ${{ runner.workspace }}/build/external/libwebrtc/build/${{ matrix.buildtype }}/obj/pc/peerconnection.lib

      - name: Upload lib binaries
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: ${{ runner.workspace }}/build/external/libwebrtc/build/${{ matrix.buildtype }}/obj/api/libjingle_peerconnection_api.lib

      - name: Upload lib binaries
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: ${{ runner.workspace }}/build/external/libwebrtc/build/${{ matrix.buildtype }}/obj/libwebrtc.a

      - name: Upload lib binaries
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: ${{ runner.workspace }}/build/external/libwebrtc/build/${{ matrix.buildtype }}/obj/pc/libpeerconnection.a

      - name: Upload lib binaries
        uses: actions/upload-artifact@v2
        with:
          name: libwebrtc-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: ${{ runner.workspace }}/build/external/libwebrtc/build/${{ matrix.buildtype }}/obj/api/libjingle_peerconnection_api.a

      - name: Upload built binary
        uses: actions/upload-artifact@v2
        with:
          name: test-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: ${{ runner.workspace }}/build/*.dll